# -*- coding: utf-8 -*-
"""HW2_Yu_Ruiqing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1znUGmgLI_yq54jPXdPMQlQFtzVeoYifQ

## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.

**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.
"""

data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

# Type your solution here
import numpy as np
import pandas as pd
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}
DF = pd.DataFrame(data)
DF.set_index("name", inplace=True)
print(DF)

Group_One = DF[(DF.family_size > DF.num_cars)]
Group_One = Group_One[(Group_One.job == "psychologist") | (Group_One.job == "teacher")]
print(Group_One)

Group_Two = DF[(DF.family_size <= 2) & (DF.num_cars >= 1)]
print(Group_Two)

print("Number of unique jobs in the dataset =", len(pd.unique(DF.job)))

"""**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**"""

import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

# Type your solution here
import numpy as np
import pandas as pd 
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
DF = {"fruit":fruit, "weights": weights}
DF1 = pd.DataFrame(DF)
print(DF1[DF1.fruit=="apple"].weights.mean())
print(DF1[DF1.fruit=="banana"].weights.mean())
print(DF1[DF1.fruit=="carrot"].weights.mean())

"""**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".

"""

import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

# Type your solution here
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])
index_of_sorted = np.argsort(course_name)
print("index_of_sorted",index_of_sorted)
starts_with_p = np.char.startswith(course_name,'P')
print("starts_with_p",starts_with_p)

"""**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.
"""

import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

# Type your solution here
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print("Original", student_id)
print("Reversed", student_id[-1::-1])

sorted = np.sort(student_id)[-1::-1]
print("Three Largest:", sorted[0:3])

"""# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**"""

# Type your solution here

# Hint: you can use arange to start off
import numpy as np
threes = np.arange(3, 100,3)
fives = np.arange(5,100,5)
union = np.union1d(threes, fives)
print(np.sum(union))

"""**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.
"""

import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

# Type your solution here
arr[:,[1,2]] = arr[:,[2,1]]
print(arr)
arr[[0,1], :] = arr[[1,0], :]
print(arr)